/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppDialer {
    }
}
declare global {
    interface HTMLAppDialerElement extends Components.AppDialer, HTMLStencilElement {
    }
    var HTMLAppDialerElement: {
        prototype: HTMLAppDialerElement;
        new (): HTMLAppDialerElement;
    };
    interface HTMLElementTagNameMap {
        "app-dialer": HTMLAppDialerElement;
    }
}
declare namespace LocalJSX {
    interface AppDialer {
    }
    interface IntrinsicElements {
        "app-dialer": AppDialer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-dialer": LocalJSX.AppDialer & JSXBase.HTMLAttributes<HTMLAppDialerElement>;
        }
    }
}
